### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by chrisg44** [woothemes/wc-api-python#75] opened 2021-09-20 15:47 UTC
N.B. I'm trying to help and leave a quick "you may have an issue here" - sorry I'm not wading through the overly long instructions that you provide.

In this documentation: https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders

The Python code is stated as:

 print(wcapi.get("orders").json())

for me this returns []

However 

print(wcapi.get("orders/#").json())

returns a list of dictionaries of the orders. 

Very minor / I might be wrong but the as written code doesn't seem to work.

**Comment by vedanshujain** [comment] 2021-10-07 09:39
Thanks for the report, I have transferred this issue to the API repo. This looks like a bug, we will take a look and fix.

**Comment by claudiosanches** [comment] 2021-10-07 14:00
I just tested and seems to be working as expected, note that there's more parameters to check the response, like `.headers`, see the library examples: https://github.com/woocommerce/wc-api-python#response

I'm closing for now since I can't reproduce this error and `wcapi.get("orders").json()` returns a list of orders to me. But please let me know if you are still having issues.

**Closed as completed by claudiosanches** 2021-10-07 14:00 UTC
Labels: bug
